import 'dotenv/config'; import express from 'express'; import mongoose from 'mongoose'; import cors from 'cors'; import morgan from 'morgan'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import multer from 'multer';
import { Product, Admin, Order, Carousel } from './models.js'; import { requireAdmin } from './auth.js'; import { createInvoice } from './invoice.js';
const app = express(), port = process.env.PORT || 5000;
const GROQ_MODELS = (process.env.GROQ_MODELS || 'not-configured').split(',').map(model => model.trim()).filter(Boolean);
const allowedOrigins = [...new Set([process.env.CLIENT_URL || 'http://localhost:5173', 'http://localhost:5173', 'http://127.0.0.1:5173'])];
app.use(cors({ origin: allowedOrigins })); app.use(express.json()); app.use(morgan('dev')); app.use('/uploads', express.static('uploads'));
const storage = multer.diskStorage({ destination: 'uploads/', filename: (_, file, cb) => cb(null, `${Date.now()}-${file.originalname.replace(/\s+/g, '-')}`) });
const upload = multer({ storage, fileFilter: (_, file, cb) => cb(null, file.mimetype.startsWith('image/')) });
app.get('/api/health', (_, res) => res.status(200).json({ status: 'online', provider: 'Groq', models: GROQ_MODELS }));
app.get('/api/carousel', async (_, res) => res.json(await Carousel.find().sort({ createdAt: -1 })));
app.post('/api/carousel', requireAdmin, async (req, res) => { if (!req.body.image) return res.status(400).json({ message: 'A carousel image is required.' }); res.status(201).json(await Carousel.create(req.body)); });
app.patch('/api/carousel/:id', requireAdmin, async (req, res) => { const slide = await Carousel.findByIdAndUpdate(req.params.id, req.body); slide ? res.json(slide) : res.status(404).json({ message: 'Slide not found.' }); });
app.delete('/api/carousel/:id', requireAdmin, async (req, res) => { const slide = await Carousel.findById(req.params.id); if (!slide) return res.status(404).json({ message: 'Slide not found.' }); await Carousel.findByIdAndDelete(req.params.id); res.status(204).end(); });
app.post('/api/auth/login', async (req, res) => { const admin = await Admin.findOne({ email: req.body.email?.toLowerCase() }); if (!admin || !await bcrypt.compare(req.body.password || '', admin.passwordHash)) return res.status(401).json({ message: 'Invalid email or password.' }); res.json({ token: jwt.sign({ id: admin._id, email: admin.email }, process.env.JWT_SECRET, { expiresIn: '12h' }), email: admin.email }); });
app.get('/api/products', async (req, res) => { const q = req.query.category ? { category: req.query.category } : {}; res.json(await Product.find(q).sort({ featured: -1, createdAt: -1 })); });
app.get('/api/products/:id', async (req, res) => { const item = await Product.findById(req.params.id); item ? res.json(item) : res.status(404).json({ message: 'Product not found.' }); });
app.post('/api/products', requireAdmin, async (req, res) => res.status(201).json(await Product.create(req.body)));
app.patch('/api/products/:id', requireAdmin, async (req, res) => { const item = await Product.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); item ? res.json(item) : res.status(404).json({ message: 'Product not found.' }); });
app.delete('/api/products/:id', requireAdmin, async (req, res) => { const product = await Product.findById(req.params.id); if (!product) return res.status(404).json({ message: 'Product not found.' }); await Product.findByIdAndDelete(req.params.id); res.status(204).end(); });
app.post('/api/upload', requireAdmin, upload.single('image'), (req, res) => req.file ? res.status(201).json({ url: `/uploads/${req.file.filename}` }) : res.status(400).json({ message: 'Choose an image.' }));
app.post('/api/orders', async (req, res) => { const { customer, items } = req.body; if (!customer?.name || !customer?.phone || !customer?.address || !Array.isArray(items) || !items.length) return res.status(400).json({ message: 'Customer and order items are required.' }); const ids = items.map(x => x.productId); const products = await Product.find({ _id: { $in: ids } }); if (products.length !== ids.length) return res.status(400).json({ message: 'A product is unavailable.' }); const lines = items.map(x => { const p = products.find(v => String(v._id) === x.productId); return { product: p._id, name: p.name, price: p.price, quantity: Math.max(1, Number(x.quantity) || 1) }; }); const subtotal = lines.reduce((s, i) => s + i.price * i.quantity, 0); const order = await Order.create({ customer, items: lines, subtotal }); res.status(201).json({ orderId: order._id, invoiceUrl: `/api/orders/${order._id}/invoice` }); });
app.get('/api/orders/:id/invoice', async (req, res) => { const order = await Order.findById(req.params.id); order ? createInvoice(res, order) : res.status(404).json({ message: 'Order not found.' }); });
app.get('/api/orders', requireAdmin, async (_, res) => res.json(await Order.find().sort({ createdAt: -1 })));
app.patch('/api/orders/:id/status', requireAdmin, async (req, res) => res.json(await Order.findByIdAndUpdate(req.params.id, { status: req.body.status }, { new: true })));
async function connectMongo() { try { if (!process.env.MONGODB_URI) throw new Error('MONGODB_URI is required.'); await mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 10000 }); const email = (process.env.ADMIN_EMAIL || 'admin@cherie.com').toLowerCase(); if (!await Admin.findOne({ email })) await Admin.create({ email, passwordHash: await bcrypt.hash(process.env.ADMIN_PASSWORD || 'ChangeMe123!', 12) }); console.log('MongoDB connected.'); } catch (error) { console.error(`MongoDB unavailable: ${error.message}`); setTimeout(connectMongo, 30000); } }
function start() { app.listen(port, () => console.log(`Cherie API online on :${port}`)); connectMongo(); }
start();
